name: Code style

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  phpstan:
    name: PHPStan (PHP ${{ matrix.php }}; Relay ${{ matrix.relay }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.2']
        relay: ['0.7.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: msgpack, igbinary, mbstring, redis, relay
          coverage: none
          tools: parallel-lint

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@v4

      - name: Check source code for syntax errors
        run: composer exec --no-interaction -- parallel-lint *.php dependencies/ includes/ tests/

      - name: Run PHPStan
        run: composer run phpstan

  editorconfig:
    name: EditorConfig
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Check EditorConfig
        uses: greut/eclint-action@v0
        with:
          eclint_args: |
            -exclude=dependencies/**/*

  plugincheck:
    name: Plugin Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Remove markdown files
        run: find . -name '*.md' -not -name 'readme.md' -delete

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
        with:
          exclude-directories: '.github,dependencies,tests'
          exclude-files: '.editorconfig,.gitattributes,.gitignore,phpunit.xml.dist'
          exclude-checks: 'prefixing'
          ignore-codes: |
            PluginCheck.CodeAnalysis.Heredoc.NotAllowed
            WordPress.DB.DirectDatabaseQuery.DirectQuery
            WordPress.DB.DirectDatabaseQuery.NoCaching
            WordPress.DB.PreparedSQL.InterpolatedNotPrepared
            WordPress.PHP.DevelopmentFunctions.error_log_error_log
            WordPress.PHP.DevelopmentFunctions.error_log_trigger_error
